/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  corePlugins: {
    // Evita el reset global de Tailwind para no alterar el tema oscuro
    // existente (CSS Modules) usado por el resto del sitio.
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        'ucr-primary': 'var(--ucr-primary)',
        'ucr-celeste': 'var(--ucr-celeste)',
        'ucr-naranja': 'var(--ucr-naranja)',
        'ucr-secondary': 'var(--ucr-secondary)',
        'ucr-secondary-container': 'var(--ucr-secondary-container)',
        'ucr-esmeralda': 'var(--ucr-esmeralda)',
        'ucr-surface': 'var(--ucr-surface)',
        'ucr-surface-container': 'var(--ucr-surface-container)',
        'ucr-surface-variant': 'var(--ucr-surface-variant)',
        'ucr-on-surface': 'var(--ucr-on-surface)',
        'ucr-on-surface-variant': 'var(--ucr-on-surface-variant)',
        'ucr-outline': 'var(--ucr-outline)',
        'ucr-outline-variant': 'var(--ucr-outline-variant)',
        'brand-esmeralda': 'var(--brand-esmeralda)',
        'brand-celeste': 'var(--brand-celeste)',
        'brand-naranja': 'var(--brand-naranja)',
        'brand-amarillo': 'var(--brand-amarillo)',
        'brand-azul': 'var(--brand-azul)',
        'brand-beige': 'var(--brand-beige)',
        'brand-rosa': 'var(--brand-rosa)',
        'brand-gris': 'var(--brand-gris)',
        // ── Tokens del rediseño Stitch (área de estudiante). Paleta Material UCR.
        //    Apuntan a variables CSS (app/globals.css) para soportar modo
        //    oscuro real vía <html class="dark"> (ver lib/useTema.ts). ──
        'primary': 'var(--st-primary)',
        'on-primary': 'var(--st-on-primary)',
        'primary-container': 'var(--st-primary-container)',
        'on-primary-container': 'var(--st-on-primary-container)',
        'secondary': 'var(--st-secondary)',
        'on-secondary': 'var(--st-on-secondary)',
        'secondary-container': 'var(--st-secondary-container)',
        'on-secondary-container': 'var(--st-on-secondary-container)',
        'secondary-fixed': 'var(--st-secondary-fixed)',
        'secondary-fixed-dim': 'var(--st-secondary-fixed-dim)',
        'primary-fixed': 'var(--st-primary-fixed)',
        'primary-fixed-dim': 'var(--st-primary-fixed-dim)',
        'tertiary': 'var(--st-tertiary)',
        'on-tertiary': 'var(--st-on-tertiary)',
        'tertiary-container': 'var(--st-tertiary-container)',
        'on-tertiary-container': 'var(--st-on-tertiary-container)',
        'on-secondary-fixed-variant': 'var(--st-on-secondary-fixed-variant)',
        'background': 'var(--st-background)',
        'on-background': 'var(--st-on-background)',
        'surface': 'var(--st-surface)',
        'on-surface': 'var(--st-on-surface)',
        'surface-variant': 'var(--st-surface-variant)',
        'on-surface-variant': 'var(--st-on-surface-variant)',
        'outline': 'var(--st-outline)',
        'outline-variant': 'var(--st-outline-variant)',
        'surface-container-lowest': 'var(--st-surface-container-lowest)',
        'surface-container-low': 'var(--st-surface-container-low)',
        'surface-container': 'var(--st-surface-container)',
        'surface-container-high': 'var(--st-surface-container-high)',
        'surface-container-highest': 'var(--st-surface-container-highest)',
        'error': 'var(--st-error)',
        'on-error': 'var(--st-on-error)',
        'error-container': 'var(--st-error-container)',
      },
      fontFamily: {
        'brand-heading': 'var(--font-brand-heading)',
        'brand-body': 'var(--font-brand-body)',
        'ucr-display': 'var(--font-ucr-display)',
        // Aliases del Stitch (mapeados a las fuentes ya cargadas en globals.css).
        'headline-lg': ['Barlow'],
        'headline-md': ['Barlow'],
        'display-lg': ['Barlow'],
        'label-caps': ['Barlow'],
        'body-base': ['Work Sans'],
        'body-semibold': ['Work Sans'],
      },
    },
  },
  plugins: [],
};
