/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  corePlugins: {
    // Evita el reset global de Tailwind para no alterar el tema oscuro
    // existente (CSS Modules) usado por el resto del sitio.
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        'ucr-primary': 'var(--ucr-primary)',
        'ucr-celeste': 'var(--ucr-celeste)',
        'ucr-naranja': 'var(--ucr-naranja)',
        'ucr-secondary': 'var(--ucr-secondary)',
        'ucr-secondary-container': 'var(--ucr-secondary-container)',
        'ucr-esmeralda': 'var(--ucr-esmeralda)',
        'ucr-surface': 'var(--ucr-surface)',
        'ucr-surface-container': 'var(--ucr-surface-container)',
        'ucr-surface-variant': 'var(--ucr-surface-variant)',
        'ucr-on-surface': 'var(--ucr-on-surface)',
        'ucr-on-surface-variant': 'var(--ucr-on-surface-variant)',
        'ucr-outline': 'var(--ucr-outline)',
        'ucr-outline-variant': 'var(--ucr-outline-variant)',
        'brand-esmeralda': 'var(--brand-esmeralda)',
        'brand-celeste': 'var(--brand-celeste)',
        'brand-naranja': 'var(--brand-naranja)',
        'brand-amarillo': 'var(--brand-amarillo)',
        'brand-azul': 'var(--brand-azul)',
        'brand-beige': 'var(--brand-beige)',
        'brand-rosa': 'var(--brand-rosa)',
        'brand-gris': 'var(--brand-gris)',
        // ── Tokens del rediseño Stitch (área de estudiante). Paleta Material UCR. ──
        'primary': '#003445',
        'on-primary': '#ffffff',
        'primary-container': '#004c63',
        'on-primary-container': '#83bbd6',
        'secondary': '#006687',
        'on-secondary': '#ffffff',
        'secondary-container': '#6acfff',
        'on-secondary-container': '#005774',
        'secondary-fixed': '#c1e8ff',
        'secondary-fixed-dim': '#73d1ff',
        'primary-fixed': '#bee9ff',
        'primary-fixed-dim': '#96ceea',
        'tertiary': '#00372c',
        'on-tertiary': '#ffffff',
        'background': '#fdf8f8',
        'on-background': '#1c1b1b',
        'surface': '#fdf8f8',
        'on-surface': '#1c1b1b',
        'surface-variant': '#e6e1e1',
        'on-surface-variant': '#40484c',
        'outline': '#70787d',
        'outline-variant': '#c0c8cd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f2f2',
        'surface-container': '#f1edec',
        'surface-container-high': '#ece7e7',
        'surface-container-highest': '#e6e1e1',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        'brand-heading': 'var(--font-brand-heading)',
        'brand-body': 'var(--font-brand-body)',
        'ucr-display': 'var(--font-ucr-display)',
        // Aliases del Stitch (mapeados a las fuentes ya cargadas en globals.css).
        'headline-lg': ['Barlow'],
        'headline-md': ['Barlow'],
        'display-lg': ['Barlow'],
        'label-caps': ['Barlow'],
        'body-base': ['Work Sans'],
        'body-semibold': ['Work Sans'],
      },
    },
  },
  plugins: [],
};
