// Catálogo predefinido para el registro de exalumnos (autodeclaración):
// facultades y carreras de la Universidad de Costa Rica. Lista de referencia
// editable desde un solo lugar.

export const FACULTADES_UCR = [
  'Facultad de Bellas Artes',
  'Facultad de Ciencias',
  'Facultad de Ciencias Agroalimentarias',
  'Facultad de Ciencias Económicas',
  'Facultad de Ciencias Sociales',
  'Facultad de Derecho',
  'Facultad de Educación',
  'Facultad de Farmacia',
  'Facultad de Ingeniería',
  'Facultad de Letras',
  'Facultad de Medicina',
  'Facultad de Microbiología',
  'Facultad de Odontología',
];

export const CARRERAS_UCR = [
  'Administración de Empresas',
  'Administración Pública',
  'Agronomía',
  'Antropología',
  'Arquitectura',
  'Artes Dramáticas',
  'Artes Plásticas',
  'Biología',
  'Bibliotecología',
  'Ciencias de la Computación e Informática',
  'Ciencias Políticas',
  'Comunicación Colectiva',
  'Contaduría Pública',
  'Derecho',
  'Diseño Gráfico',
  'Economía',
  'Educación Primaria',
  'Enfermería',
  'Enseñanza de la Matemática',
  'Estadística',
  'Farmacia',
  'Filología',
  'Filosofía',
  'Física',
  'Geografía',
  'Geología',
  'Historia',
  'Ingeniería Agrícola',
  'Ingeniería Civil',
  'Ingeniería Eléctrica',
  'Ingeniería Industrial',
  'Ingeniería Mecánica',
  'Ingeniería Química',
  'Ingeniería en Computadores',
  'Matemática',
  'Medicina y Cirugía',
  'Mercadeo',
  'Microbiología y Química Clínica',
  'Música',
  'Nutrición',
  'Odontología',
  'Psicología',
  'Química',
  'Sociología',
  'Trabajo Social',
  'Turismo',
];
